#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.1.2
# Product:       stcc4
# Model-Version: 3.0.0
#

import argparse
import time
from sensirion_i2c_driver import I2cConnection, CrcCalculator
from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import (SensorBridgePort,
                                          SensorBridgeShdlcDevice,
                                          SensorBridgeI2cProxy)
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_stcc4.device import Stcc4Device

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM1')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=460800) as port:
    bridge = SensorBridgeShdlcDevice(ShdlcConnection(port), slave_address=0)
    bridge.set_i2c_frequency(SensorBridgePort.ONE, frequency=100e3)
    bridge.set_supply_voltage(SensorBridgePort.ONE, voltage=3.3)
    bridge.switch_supply_on(SensorBridgePort.ONE)
    i2c_transceiver = SensorBridgeI2cProxy(bridge, port=SensorBridgePort.ONE)
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x64,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Stcc4Device(channel)
    time.sleep(0.006)

    # Ensure sensor is in idle state
    sensor.exit_sleep_mode()
    sensor.stop_continuous_measurement()

    # Enter sleep mode
    sensor.enter_sleep_mode()
    for i in range(100):

        #     Measure every 10 seconds.
        time.sleep(10.0)

        #     Exit sleep mode to put the sensor into idle mode
        #     to be able to perform a single shot measurement
        sensor.exit_sleep_mode()

        #     If humidity/temperature and/or pressure compensation is
        #     desired, you should call the respective compensation
        #     functions here. Check-out the header file for the definition
        #     of the compensation functions.

        #     Perform a single shot measurement and read the sensor data
        sensor.measure_single_shot()
        (co2_concentration, temperature, relative_humidity, status
         ) = sensor.read_measurement()

        #     Power down the sensor to reduce power consumption.
        sensor.enter_sleep_mode()

        #     Print results as physical unit.
        print(f"CO2 concentration [ppm] = {co2_concentration}"
              )
        print(f"Temperature [°C] = {temperature}"
              )
        print(f"Humidity [RH] = {relative_humidity}"
              )
        print(f"Status = {status}"
              )
