name: Publish Documentation
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  documentation:
      uses: sensirion/.github/.github/workflows/driver.python.documentation.yml@main
