name: Validate and Test Python Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    uses: sensirion/.github/.github/workflows/driver.python.test.yml@main
